name: Hangman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: [portfolio-hangman]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Required Modules
        run: |
          bun install

      - name: Build the Project
        run: |
          bun run build

      - name: Restart App
        run: |
          pm2 stop "Hangman"
          pm2 reset "Hangman"
          pm2 start "Hangman"

    #PM2 START COMMAND: pm2 start bun "run start" --name "APP_NAME"
